name: Deploy to Hostinger

on:
  push:
    branches:
      - dev
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build:prod

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Determine Target Directory
        id: set-target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "TARGET_PATH=${{ secrets.PROD_PATH }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "TARGET_PATH=${{ secrets.STAGING_PATH }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TARGET_PATH=${{ secrets.DEV_PATH }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Hostinger via Rsync
        uses: up9cloud/action-rsync@v1
        with:
          args: |
            -e "ssh -p ${{ secrets.SFTP_PORT }} -o StrictHostKeyChecking=no" \
            -avz --delete-excluded \
            --exclude='.git' --exclude='.gitignore' --exclude='node_modules' --exclude='vendor' \
            --exclude='.env' --exclude='security.txt' --exclude='to-do-list.txt' --exclude='file-structure.txt' \
            --exclude='README.md' --exclude='deploy.yml' --exclude='.idea' --exclude='database/migrations' --exclude='tests' \
            ./ u102329302@147.93.42.133:${{ env.TARGET_PATH }}
